#!/usr/bin/env python3
# font_to_header.py - convert a .ttf/.otf into a C header byte array for embedding.
#
# Output matches the existing embedded fonts (e.g. SFProDisplayRegular.h):
#   inline unsigned char <VarName>[] = { 0x.., 0x.., ... };
# load it with io.Fonts->AddFontFromMemoryTTF(<VarName>, sizeof(<VarName>), ...)
# (set ImFontConfig::FontDataOwnedByAtlas = false - these arrays are static).
#
# Usage:
#   python font_to_header.py <input.ttf> <VarName> <output.h> [--subset]
#
# --subset (needs `pip install fonttools brotli`): keep only Basic Latin +
#   Latin-1 Supplement + Cyrillic glyphs (the menu's non-CJK range). Shrinks
#   big fonts a lot (Montserrat 330KB -> ~60KB). CJK kana is merged from
#   msgothic at load time, so the menu face never needs it.
import sys, os, tempfile

# Unicode ranges the menu font actually rasterizes (see fontRange in Render.cpp,
# minus the kana/fullwidth blocks which come from msgothic).
SUBSET_UNICODES = "U+0020-00FF,U+0400-04FF,U+2000-206F"

def subset_font(in_path):
    from fontTools import subset
    out_fd, out_path = tempfile.mkstemp(suffix=os.path.splitext(in_path)[1])
    os.close(out_fd)
    args = [
        in_path,
        f"--unicodes={SUBSET_UNICODES}",
        "--layout-features=*",   # keep kerning/ligatures for the kept glyphs
        "--no-hinting",
        "--desubroutinize",
        f"--output-file={out_path}",
    ]
    subset.main(args)
    return out_path

def write_header(data, var_name, out_path):
    with open(out_path, "w", newline="\n") as f:
        f.write(f"// Generated by tools/font_to_header.py\n")
        f.write(f"// File size: {len(data)}\n")
        f.write(f"inline unsigned char {var_name}[] = {{\n")
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02X}" for b in data[i:i+16])
            f.write(f"\t{row},\n")
        f.write("};\n")

def main():
    if len(sys.argv) < 4:
        print("usage: python font_to_header.py <input.ttf> <VarName> <output.h> [--subset]")
        sys.exit(1)
    in_path, var_name, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    do_subset = "--subset" in sys.argv[4:]

    src = in_path
    tmp = None
    if do_subset:
        tmp = subset_font(in_path)
        src = tmp
    with open(src, "rb") as f:
        data = f.read()
    if tmp:
        os.remove(tmp)

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    write_header(data, var_name, out_path)
    print(f"{out_path}: {len(data)} bytes -> {var_name}[]")

if __name__ == "__main__":
    main()
