name: MSBuild

on:
  workflow_dispatch:

jobs:
  msbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - name: Restore NuGet
      run: nuget restore
    - name: Build
      run: msbuild Amalgam.sln /p:Platform=x64 /p:Configuration=ReleaseFreetypeAVX2
    - uses: actions/upload-artifact@v4
      with:
        name: AmalgamDLL
        path: output/x64/ReleaseFreetypeAVX2/*.dll
